@startuml BiboAnime

    package databaseLiteDB {
        class databaseConfig {
            + {static} string locationOfDataBase
        }

        class databaseController {
            + int resetDataBaseAnimes()
            + void addAnimeToDB(AnimeData animeToAdd)
            + bool deleteAnimeFromDB(AnimeData animeToDelete)
            + void updateAnime(AnimeData animeToUpdate)
            + List<AnimeData> getAllAnimes()
            + List<AnimeRow> getAllAnimesAsRow()
            + AnimeData getAnimeById(Guid id)
            + AnimeData getAnimeByName(string name)
            + List<AnimeData> getByOneTag(AnimeTag tag)
            + List<AnimeData> getByListOfTags(List<AnimeTag> tags)
            + List<AnimeData> getByTier(AnimeTier animeTier)
            + bool checkIfAnimeExist(string name)
            + void addOneTag(AnimeTag tag)
            + void addImportedTags(List<AnimeTag> tagList)
            + AnimeTag getTagByDesignator(string designator)
            + int resetDataBaseTags()
            + List<AnimeTag> getAllAnimeTags()
            + List<AnimeTag> getAllUsedTags()
            + int getTagDbCountForIdPlusOne()
            + bool checkIfTagExistsByDesignator(AnimeTag animeTag)
            + bool checkIfTagExistsByDesignator(AnimeTag animeTag, LiteDatabase db)
            + bool deleteOneTag(AnimeTag tagToDelete)
        }

        class databaseFilterController {
            + List<AnimeData> dbFilterTier(AnimeTier tierToFilter)
            + List<AnimeData> dbFilterByTag(List<AnimeTag> filterTags)
            + List<AnimeData> dbFilterWithoutTag(List<AnimeTag> filterTags)
            + List<AnimeData> dbFilterTagAndTier(AnimeTier filterTier, List<AnimeTag> filterTags)
            + List<AnimeData> dbFilterRatingMinGeneral(int minGeneralRating)
            + List<AnimeData> dbFilterIsFav(bool fav)
            + List<AnimeData> dbFilterRatingMinABCDE(int minGeneral = 0, int minStory = 0, int minSound = 0, int minAnimation = 0, int minSpecialEffect = 0, int minGermanDub = 0)
            + List<AnimeData> dbFilterRatingCheckGermanDub(bool dub)
            + List<AnimeData> dbFilterMinMaxStaffeln(bool max, int amount) {
            using (var db = new LiteDatabase(databaseConfigs.locationOfDataBase))
            + List<AnimeData> dbFilterMinMaxEpisodesTotal(bool max, int amount)
            + List<AnimeData> dbFilterCheckRecommendation(bool exist, bool existnot)
        }
    }

    package datatypes {
        
        class AnimeData {
            + Guid id
            + bool favorite
            + string name
            + string originalName
            + Rating rating
            + List<AnimeTag> tags
            + string urlAnimePlanet
            + AnimeStatus status
            + List<Staffel> staffeln
            + int episodesTotal
            + int movies
            + int ovh
            + string thirdPartyRecommendation
            + AnimeTier tier
        }

        class AnimeFilterTier {
            + int id
            + AnimeTier tier
            + string name
            + Rating rating
            + List<AnimeTag> animeTag
        }

        class AnimeRow {
            + int id
            + bool favorite
            + string name
            + int generalRating
            + string tags
            + AnimeStatus status
        }

        enum AnimeStatus {
            Abgebrochen
            Angefangen
            Fertig
            Unterbrochen
            Wunschliste
        }

        class AnimeTag {
            + Guid id
            + string tagDesignator

            + AnimeTag()
            + AnimeTag(Guid id, string tagDesignator)

            + public AnimeTag(Guid id, string tagDesignator)
            + public bool EqualTag(AnimeTag a, AnimeTag b)
            + bool EqualsList(List<AnimeTag> a, List<AnimeTag> b)
        }

        enum AnimeTier {
            S
            A
            B
            C
            D
            Dummy
        }

        class Rating {
            + int story
            + int sound
            + int animation
            + int specialEffect
            + int germanDub
            + int general

            + Rating(int story, int sound, int animation, int specialEffect, int germanDub)
            + bool Equals(Rating a, Rating b)
        }

        class Staffeln {
            + int counter
            + int episodes

            + bool EqualStaffel(Staffel a, Staffel b)

            + bool EqualsList(List<Staffel> a, List<Staffel> b)
        }
    }

    package ImportExport {
        class Export {
            + {static} bool exportAnimeList(string filePath)
            + {static} bool exportAnimeTags(string filePath)
            - {static} string convertToCsvLine(AnimeTag tag)
            - {static} string convertToCsvLine(AnimeData animeData)
        }

        class Import {
            + {static} bool importAnimeList()
            + {static} void importAnimeTags(string filePath, bool importToDataBase) 
            + {static} bool checkTagListValid(string filePath)
            - {static} List<AnimeTag> craftTagOutOfLine(List<string> csvLines)
        }
    }

@enduml