<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<NeutralLanguage>de</NeutralLanguage>

		<Version>2.0.6</Version>
		<FileVersion>$(Version)</FileVersion>
		<InformationalVersion>$(Version)</InformationalVersion>
		<Title>Anicluster</Title>
		<Description></Description>
	</PropertyGroup>
	
	<Target Name="WriteVersionToFile" AfterTargets="Publish">
		<WriteLinesToFile File="$(PublishDir)version.txt" Lines="$(Version)" Overwrite="true" />
	</Target>
	<!--<Target Name="Setup" AfterTargets="Publish">
		<Exec Command="'C:\Program Files (x86)\Inno Setup 6\ISCC.exe' '$(ProjectDir)..\InnoSetup\setupSkript.iss'" />
	</Target>-->

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.Sqlite.Core" Version="8.0.10" />
		<PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
		<PackageReference Include="SQLitePCLRaw.bundle_green" Version="2.1.10" />
		<PackageReference Include="WpfMath" Version="2.1.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Modells\Modells.csproj" />
	</ItemGroup>

</Project>
