INSERT INTO
    Tag (Designation)
VALUES
    ("Abenteuer"),
    ("Action"),
    ("Androiden"),
    ("Apokalypse"),
    ("Battle-Royal"),
    ("Crossover"),
    ("Dark-Fantasy"),
    ("Demi"),
    ("Demonen"),
    ("Drachen"),
    ("Drama"),
    ("Dungeon"),
    ("Ecchi"),
    ("Elfen"),
    ("Engel"),
    ("Fantasy"),
    ("Feuerwehr"),
    ("Gefängniss"),
    ("Geheime Identität"),
    ("Gott"),
    ("Harem"),
    ("Heirat"),
    ("Historie (Geschichte)"),
    ("Horror"),
    ("Hunde"),
    ("Isekai"),
    ("Katzen"),
    ("Komödie"),
    ("Krankenhaus"),
    ("Krieg"),
    ("Krimi"),
    ("Magie"),
    ("Management"),
    ("Mecha"),
    ("Medizin"),
    ("Militär"),
    ("Mittelalter"),
    ("Monster"),
    ("Mysterik"),
    ("Over-Powered (OP)"),
    ("Parodie"),
    ("Politik"),
    ("Polizei"),
    ("Post-Apokalypse"),
    ("Psychothriller"),
    ("Reincarnation"),
    ("Religion"),
    ("Reserve Harem"),
    ("Rivalität"),
    ("Romanze"),
    ("Royal"),
    ("Samurai"),
    ("Schwertkampf"),
    ("Sci-Fiction"),
    ("Seinen"),
    ("Skelette"),
    ("Slice-Of-Life"),
    ("Sport"),
    ("Thriller"),
    ("Tiere"),
    ("Tragödie"),
    ("Übermäßige Gewaltdarstellung"),
    ("Vampire"),
    ("Virtuelle Realität (VR)"),
    ("Wirtschaft"),
    ("Zeitreise"),
    ("Zombie");
