; Script generated by the Inno Script Studio Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Anicluster"
#define MyAppVersion "1.0"
#define MyAppPublisher "Kretchen001"
#define MyAppExeName "Anicluster.bat"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{4DACC09A-0C9C-40CE-A0B4-0A240F902801}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={pf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
InfoBeforeFile=D:\Visual_Studio_C#\Anicluster\InnoSetup\ReadMe.txt
OutputDir=D:\Visual_Studio_C#\Anicluster\InnoSetup
OutputBaseFilename=setup_v1_0
Password=Anicluster
Encryption=yes
Compression=lzma
SolidCompression=yes

[Languages]
Name: "german"; MessagesFile: "compiler:Languages\German.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 0,6.1

[Files]
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\Anicluster.exe"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\Accessibility.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\Anicluster.deps.json"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\Anicluster.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\Anicluster.pdb"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\Anicluster.runtimeconfig.json"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-core-console-l1-1-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-core-console-l1-2-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-core-datetime-l1-1-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-core-debug-l1-1-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-core-errorhandling-l1-1-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-core-fibers-l1-1-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-core-file-l1-1-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-core-file-l1-2-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-core-file-l2-1-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-core-handle-l1-1-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-core-heap-l1-1-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-core-interlocked-l1-1-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-core-libraryloader-l1-1-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-core-localization-l1-2-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-core-memory-l1-1-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-core-namedpipe-l1-1-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-core-processenvironment-l1-1-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-core-processthreads-l1-1-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-core-processthreads-l1-1-1.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-core-profile-l1-1-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-core-rtlsupport-l1-1-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-core-string-l1-1-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-core-synch-l1-1-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-core-synch-l1-2-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-core-sysinfo-l1-1-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-core-timezone-l1-1-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-core-util-l1-1-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-crt-conio-l1-1-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-crt-convert-l1-1-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-crt-environment-l1-1-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-crt-filesystem-l1-1-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-crt-heap-l1-1-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-crt-locale-l1-1-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-crt-math-l1-1-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-crt-multibyte-l1-1-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-crt-private-l1-1-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-crt-process-l1-1-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-crt-runtime-l1-1-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-crt-stdio-l1-1-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-crt-string-l1-1-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-crt-time-l1-1-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\api-ms-win-crt-utility-l1-1-0.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\BiboAnime.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\BiboAnime.pdb"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\clretwrc.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\clrjit.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\coreclr.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\createdump.exe"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\D3DCompiler_47_cor3.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\dbgshim.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\DirectWriteForwarder.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\hostfxr.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\hostpolicy.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\LiteDB.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\Microsoft.CSharp.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\Microsoft.DiaSymReader.Native.amd64.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\Microsoft.VisualBasic.Core.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\Microsoft.VisualBasic.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\Microsoft.VisualBasic.Forms.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\Microsoft.Win32.Primitives.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\Microsoft.Win32.Registry.AccessControl.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\Microsoft.Win32.Registry.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\Microsoft.Win32.SystemEvents.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\mscordaccore.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\mscordaccore_amd64_amd64_6.0.622.26707.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\mscordbi.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\mscorlib.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\mscorrc.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\msquic.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\netstandard.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\PenImc_cor3.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\PresentationCore.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\PresentationFramework.Aero.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\PresentationFramework.Aero2.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\PresentationFramework.AeroLite.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\PresentationFramework.Classic.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\PresentationFramework.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\PresentationFramework.Luna.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\PresentationFramework.Royale.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\PresentationFramework-SystemCore.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\PresentationFramework-SystemData.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\PresentationFramework-SystemDrawing.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\PresentationFramework-SystemXml.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\PresentationFramework-SystemXmlLinq.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\PresentationNative_cor3.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\PresentationUI.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\ReachFramework.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.AppContext.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Buffers.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.CodeDom.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Collections.Concurrent.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Collections.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Collections.Immutable.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Collections.NonGeneric.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Collections.Specialized.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.ComponentModel.Annotations.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.ComponentModel.DataAnnotations.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.ComponentModel.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.ComponentModel.EventBasedAsync.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.ComponentModel.Primitives.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.ComponentModel.TypeConverter.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Configuration.ConfigurationManager.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Configuration.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Console.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Core.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Data.Common.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Data.DataSetExtensions.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Data.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Design.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Diagnostics.Contracts.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Diagnostics.Debug.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Diagnostics.DiagnosticSource.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Diagnostics.EventLog.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Diagnostics.FileVersionInfo.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Diagnostics.PerformanceCounter.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Diagnostics.Process.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Diagnostics.StackTrace.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Diagnostics.TextWriterTraceListener.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Diagnostics.Tools.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Diagnostics.TraceSource.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Diagnostics.Tracing.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.DirectoryServices.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Drawing.Common.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Drawing.Design.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Drawing.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Drawing.Primitives.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Dynamic.Runtime.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Formats.Asn1.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Globalization.Calendars.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Globalization.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Globalization.Extensions.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.IO.Compression.Brotli.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.IO.Compression.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.IO.Compression.FileSystem.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.IO.Compression.Native.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.IO.Compression.ZipFile.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.IO.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.IO.FileSystem.AccessControl.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.IO.FileSystem.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.IO.FileSystem.DriveInfo.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.IO.FileSystem.Primitives.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.IO.FileSystem.Watcher.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.IO.IsolatedStorage.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.IO.MemoryMappedFiles.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.IO.Packaging.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.IO.Pipes.AccessControl.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.IO.Pipes.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.IO.UnmanagedMemoryStream.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Linq.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Linq.Expressions.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Linq.Parallel.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Linq.Queryable.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Memory.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Net.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Net.Http.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Net.Http.Json.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Net.HttpListener.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Net.Mail.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Net.NameResolution.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Net.NetworkInformation.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Net.Ping.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Net.Primitives.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Net.Quic.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Net.Requests.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Net.Security.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Net.ServicePoint.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Net.Sockets.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Net.WebClient.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Net.WebHeaderCollection.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Net.WebProxy.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Net.WebSockets.Client.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Net.WebSockets.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Numerics.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Numerics.Vectors.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.ObjectModel.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Printing.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Private.CoreLib.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Private.DataContractSerialization.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Private.Uri.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Private.Xml.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Private.Xml.Linq.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Reflection.DispatchProxy.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Reflection.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Reflection.Emit.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Reflection.Emit.ILGeneration.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Reflection.Emit.Lightweight.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Reflection.Extensions.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Reflection.Metadata.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Reflection.Primitives.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Reflection.TypeExtensions.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Resources.Extensions.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Resources.Reader.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Resources.ResourceManager.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Resources.Writer.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Runtime.CompilerServices.Unsafe.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Runtime.CompilerServices.VisualC.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Runtime.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Runtime.Extensions.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Runtime.Handles.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Runtime.InteropServices.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Runtime.InteropServices.RuntimeInformation.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Runtime.Intrinsics.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Runtime.Loader.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Runtime.Numerics.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Runtime.Serialization.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Runtime.Serialization.Formatters.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Runtime.Serialization.Json.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Runtime.Serialization.Primitives.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Runtime.Serialization.Xml.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Security.AccessControl.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Security.Claims.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Security.Cryptography.Algorithms.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Security.Cryptography.Cng.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Security.Cryptography.Csp.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Security.Cryptography.Encoding.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Security.Cryptography.OpenSsl.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Security.Cryptography.Pkcs.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Security.Cryptography.Primitives.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Security.Cryptography.ProtectedData.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Security.Cryptography.X509Certificates.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Security.Cryptography.Xml.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Security.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Security.Permissions.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Security.Principal.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Security.Principal.Windows.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Security.SecureString.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.ServiceModel.Web.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.ServiceProcess.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Text.Encoding.CodePages.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Text.Encoding.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Text.Encoding.Extensions.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Text.Encodings.Web.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Text.Json.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Text.RegularExpressions.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Threading.AccessControl.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Threading.Channels.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Threading.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Threading.Overlapped.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Threading.Tasks.Dataflow.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Threading.Tasks.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Threading.Tasks.Extensions.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Threading.Tasks.Parallel.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Threading.Thread.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Threading.ThreadPool.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Threading.Timer.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Transactions.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Transactions.Local.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.ValueTuple.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Web.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Web.HttpUtility.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Windows.Controls.Ribbon.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Windows.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Windows.Extensions.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Windows.Forms.Design.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Windows.Forms.Design.Editors.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Windows.Forms.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Windows.Forms.Primitives.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Windows.Input.Manipulations.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Windows.Presentation.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Xaml.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Xml.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Xml.Linq.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Xml.ReaderWriter.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Xml.Serialization.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Xml.XDocument.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Xml.XmlDocument.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Xml.XmlSerializer.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Xml.XPath.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\System.Xml.XPath.XDocument.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\ucrtbase.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\UIAutomationClient.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\UIAutomationClientSideProviders.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\UIAutomationProvider.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\UIAutomationTypes.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\vcruntime140_cor3.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\WindowsBase.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\WindowsFormsIntegration.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\wpfgfx_cor3.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
Source: "Anicluster.bat"; DestDir: "{app}"
Source: "..\Anicluster\bin\Publish\net6.0-windows\win-x86\databaseLiteDB\database.liteDB"; DestDir: "{app}\prog\databaseLiteDB"

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Dirs]
Name: "{app}\prog"
Name: "{app}\prog\databaseLiteDB"
