; Script generated by the Inno Script Studio Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Anicluster"
#define MyAppPublisher "Kretchen001"
#define MyAppExeName "Anicluster.exe"

[Setup]
AppId={{4DACC09A-0C9C-40CE-A0B4-0A240F902802}
AppName={#MyAppName}
AppVersion={code:GetAppVersion}
AppVerName={#MyAppName} {code:GetAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={pf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
InfoBeforeFile=D:\Visual_Studio_C#\Anicluster\InnoSetup\ReadMe.txt
OutputDir=D:\Visual_Studio_C#\Anicluster\InnoSetup
OutputBaseFilename=setup_{#MyAppName}_v_XXX
Password=Anicluster
Encryption=yes
Compression=lzma
SolidCompression=yes
PrivilegesRequired=none

[Languages]
Name: "german"; MessagesFile: "compiler:Languages\German.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 0,6.1

[Files]
Source: "..\Anicluster\bin\Publish\Anicluster.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\Anicluster.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\D3DCompiler_47_cor3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\e_sqlite3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\Modells.pdb"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\PenImc_cor3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\PresentationNative_cor3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\vcruntime140_cor3.dll"; DestDir: "{app}"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\wpfgfx_cor3.dll"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

;[Dirs]               ; aktuell nicht wegen Programmlogik
;Name: "{app}\db"     ; aktuell nicht wegen Programmlogik
;Name: "{app}\logs"   ; aktuell nicht wegen Programmlogik

[UninstallRun]
Filename: "{app}\logs"; Flags: skipifdoesntexist
Filename: "{app}\db"; Flags: skipifdoesntexist

[PostCompile]
Name: "renameForVersion.bat"; Flags: runminimized cmdprompt redirectoutput

[Code]
function GetAppVersion(Param: string): string;
var                 
  VersionFile: string;
  Lines: TArrayOfString;
begin
  // Der Pfad zur versions.txt, die durch MSBuild erzeugt wurde
  VersionFile := '..\Anicluster\bin\Publish\version.txt'; 
  if FileExists(VersionFile) then
  begin
    // Die Versionsnummer aus der version.txt lesen
    LoadStringsFromFile(VersionFile, Lines); 
    if Length(Lines) > 0 then
      Result := Lines[0]  // Setze die erste Zeile als Versionsnummer
    else
      Result := '0.0.0';   // Fallback, falls die Datei leer ist        
  end
  else
  begin
    // Falls die Datei nicht existiert, setze eine Standardversion
    Result := '0.0.0';
  end;
end;
          