; Script generated by the Inno Script Studio Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Anicluster"
#define MyAppVersion "1.1.0"
#define MyAppPublisher "Kretchen001"
#define MyAppExeName "Anicluster.bat"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{4DACC09A-0C9C-40CE-A0B4-0A240F902801}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
DefaultDirName={pf}\{#MyAppName}
DefaultGroupName={#MyAppName}
AllowNoIcons=yes
InfoBeforeFile=C:\Users\Tim\Documents\Eigenes\Anicluster\InnoSetup\ReadMe.txt
OutputDir=C:\Users\Tim\Documents\Eigenes\Anicluster\InnoSetup
OutputBaseFilename=setup_v1_1_0
Password=Anicluster
Encryption=yes
Compression=lzma
SolidCompression=yes

[Languages]
Name: "german"; MessagesFile: "compiler:Languages\German.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked; OnlyBelowVersion: 0,6.1

[Code]
var
  CustomPage: TWizardPage;
  LabelText: TLabel;
  LabelText2: TLabel;

procedure InitializeWizard;
begin
  // Erstellen Sie eine benutzerdefinierte Seite
  CustomPage := CreateCustomPage(wpWelcome, 'Hinweis', 'Dies ist Update!');

  LabelText := TLabel.Create(WizardForm);
  LabelText.Parent := CustomPage.Surface;
  LabelText.Left := 16;
  LabelText.Top := 16;
  LabelText.Caption := 'Dieses Update benötigt zum Ausführen die Grundversion "Anicluster 1.0.x" oder';
  LabelText2 := TLabel.Create(WizardForm);
  LabelText2.Parent := CustomPage.Surface;
  LabelText2.Left := 16;
  LabelText2.Top := LabelText.Top + LabelText.Height + 16;
  LabelText2.Caption := 'eine vollständige Installation von dotNet 6.0!';
end;

[Files]
Source: "..\Anicluster\bin\Publish\LiteDB.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\BiboAnime.pdb"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\BiboAnime.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\Anicluster.runtimeconfig.json"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\Anicluster.pdb"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\Anicluster.exe"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\Anicluster.dll"; DestDir: "{app}\prog"; Flags: ignoreversion
Source: "..\Anicluster\bin\Publish\Anicluster.deps.json"; DestDir: "{app}\prog"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files
Source: "Anicluster.bat"; DestDir: "{app}"

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: quicklaunchicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

[Dirs]
Name: "{app}\prog"
Name: "{app}\prog\databaseLiteDB"
